Models/City.cs
namespace MyFileUploader.Models
{
    public class City
    {
        public int Id { get; set; }
        public string Name { get; set; }

    }
}

Models/ErrorViewModel.cs
namespace MyFileUploader.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyFileUploader.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AboutView()
        {
            return View();
        }
    }
}

Controllers/CityController.cs
using Microsoft.AspNetCore.Mvc;
using MyFileUploader.Models;
using System.Collections.Generic;
using System.Linq;


namespace MyFileUploader.Controllers
{
    public class CityController : Controller
    {
        [HttpGet("CityController")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost("CityController")]
        public JsonResult Index(string Prefix)
        {
            //Note : you can bind same list from database  
            List<City> ObjList = new List<City>()
            {

                new City {Id=1,Name="Latur" },
                new City {Id=2,Name="Mumbai" },
                new City {Id=3,Name="Pune" },
                new City {Id=4,Name="Delhi" },
                new City {Id=5,Name="Dehradun" },
                new City {Id=6,Name="Noida" },
                new City {Id=7,Name="New Delhi" }

        };
            //Searching records from list using LINQ query  
            var Name = (from N in ObjList
                        where N.Name.StartsWith(Prefix)
                        select new { N.Name });
            return Json(Name);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyFileUploader.Models;
using System.Diagnostics;

namespace MyFileUploader.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/About/AboutView.cshtml
@{
    ViewData["Title"] = "About Us";
    ViewData["Subs"] = "Genuine Information";
}
<h1>@ViewData["Title"]</h1>
<h2>@ViewData["Subs"]</h2>

<p>This web application has been developed by using ASP.NET Core MVC.</p>

<p>Thanks you!!!</p>

<p>You have checked in here last at : @DateTime.Now</p>

Views/City/Index.cshtml
@model MyFileUploader.Models.City

@{    
    ViewBag.Title = "www.compilemode.com";    
}

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">    
<script src="//code.jquery.com/jquery-1.10.2.js"></script>    
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>    
<script type="text/javascript">    
    $(document).ready(function () {    
        $("#Name").autocomplete({    
            source: function (request, response) {    
                $.ajax({    
                    url: "/Home/Index",    
                    type: "POST","GET",    
                    dataType: "json",    
                    data: { Prefix: request.term },    
                    success: function (data) {    
                        response($.map(data, function (item) {    
                            return { label: item.Name, value: item.Name};    
                        }))    
    
                    }    
                })    
            },    
            messages: {    
                noResults: "", results: ""    
            }    
        });    
    })    
</script>    
@using (Html.BeginForm())    
{    
    @Html.AntiForgeryToken()    
    
    <div class="form-horizontal">    
        <h1 class="display-3">City Filter</h1>
    
        <hr />    
    
        <div class="form-group">    
    
            <div class="col-md-12">   
                <p>You can search for your city here!!!</p>
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })    
    
            </div>    
        </div>    
    
    </div>    
} 
<p class="mt-5 font-monospace text-warning bg-dark fs-4">Select Your City and proceed further.</p>

Views/FileUpload/Index.cshtml
@{
    ViewData["Title"] = "File Upload";
    ViewData["Subs"] = "Upload your files here";
}
<h1>@ViewData["Title"]</h1>
<h2>@ViewData["Subs"]</h2>

<form method="post" enctype="multipart/form-data" asp-controller="FileUpload" asp-action="Index">
    <div class="form-group">
        <div class="col-md-10">
            <p>Upload files of size less than 1MB (in txt format)</p>
            <input type="file" name="files" accept=".txt" maxlength="1024"/>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Upload" />                    
        </div>
    </div>
</form>
<p class="mt-3 font-monospace text-warning bg-blue fs-3">@ViewBag.Message</p>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to File Uploader</h1>
    <h2 class="display-8">You can upload here!!!</h2>
    <p>To visit Azure Portal <a href="https://portal.azure.com/#home">Click here</a>.</p>
</div>

Views/OTPgenerator/Index.cshtml
@{
    ViewBag.Title = "Generate OTP";
}

@using (Html.BeginForm("GenerateNumericOTP", "OTPgenerator"))
{
    <table>
        <tr>
            <td>Click on button to Generate Numeric OTP :</td>
            <td><input id="Submit1" type="submit" value="Generate OTP" /></td>
        </tr>
        <tr>
            <td></td>
            <td>@ViewBag.otp</td>
        </tr>
    </table>
}
@using (Html.BeginForm("GenerateAlphaNumericOTP", "OTPgenerator"))
{
    <table>
        <tr>
            <td>Click on button to Generate Alphanumeric OTP :</td>
            <td><input id="Submit1" type="submit" value="Generate OTP" /></td>
        </tr>
        <tr>
            <td></td>
            <td>@ViewBag.anotp</td>
        </tr>
    </table>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFileUploader</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyFileUploader.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyFileUploader</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="AboutView">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FileUpload" asp-action="Index">Upload Files</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OTPgenerator" asp-action="Index">Generate OTP</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Index">Search City</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MyFileUploader - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>